export const RiskCols = [
  {
    label: "Patient Nat I.D",
    name: "patientId",
    type: "text",
    placeholder: "Enter ID number (e.g., 12345678)",
  },
  {
    label: "Patient Phone",
    name: "patientPhone",
    type: "text",
    placeholder: "Enter phone number (e.g., 0781234567)",
  },
  {
    label: "Age",
    name: "age",
    type: "number",
    placeholder: "Enter age (e.g., 45)",
  },
  {
    label: "Gender",
    name: "sex",
    type: "select",
    options: ["Male", "Female"],
    placeholder: "Select gender",
  },
  {
    label: "Chest Pain Type (cp)",
    name: "cp",
    type: "number",
    placeholder: "Enter value (e.g., 1)",
  },
  {
    label: "Resting Blood Pressure (restbp)",
    name: "restbp",
    type: "number",
    placeholder: "Enter blood pressure (e.g., 120)",
  },
  {
    label: "Cholesterol (chol)",
    name: "chol",
    type: "number",
    placeholder: "Enter cholesterol level (e.g., 200)",
  },
  {
    label: "Fasting Blood Sugar (fbs)",
    name: "fbs",
    type: "number",
    placeholder: "Enter fasting blood sugar level (e.g., 120)",
  },
  {
    label: "Resting Electrocardiographic (restecg)",
    name: "restecg",
    type: "number",
    placeholder: "Enter value (e.g., 0)",
  },
  {
    label: "Maximum Heart Rate (thalach)",
    name: "thalach",
    type: "number",
    placeholder: "Enter heart rate (e.g., 150)",
  },
  {
    label: "Exercise Induced Angina (exang)",
    name: "exang",
    type: "number",
    placeholder: "Enter value (e.g., 0)",
  },
  {
    label: "Oldpeak",
    name: "oldpeak",
    type: "number",
    placeholder: "Enter value (e.g., 2.3)",
  },
  {
    label: "Slope",
    name: "slope",
    type: "number",
    placeholder: "Enter value (e.g., 1)",
  },
  {
    label: "Number of Major Vessels (ca)",
    name: "ca",
    type: "number",
    placeholder: "Enter number of vessels (e.g., 0)",
  },
  {
    label: "Thalassemia (thal)",
    name: "thal",
    type: "number",
    placeholder: "Enter value (e.g., 3)",
  },
  {
    label: "BMI",
    name: "BMI",
    type: "number",
    placeholder: "Enter BMI (e.g., 24)",
  },
  {
    label: "Family History",
    name: "familyHistory",
    type: "text",
    placeholder: "Enter family medical history",
  },
  {
    label: "Smoking Status",
    name: "smokingStatus",
    type: "text",
    placeholder: "Enter smoking status (e.g., Never Smoked, Former Smoker, Current Smoker)",
  },
  {
    label: "Physical Activity",
    name: "physicalActivity",
    type: "text",
    placeholder: "Enter physical activity level (e.g., Sedentary, Moderate, Active)",
  },
  {
    label: "Serum Creatinine",
    name: "serumCreatinine",
    type: "number",
    placeholder: "Enter creatinine level (e.g., 1.2)",
  },
  {
    label: "HbA1c",
    name: "HbA1c",
    type: "number",
    placeholder: "Enter HbA1c level (e.g., 6.0)",
  },
  {
    label: "Urine Protein",
    name: "urineProtein",
    type: "number",
    placeholder: "Enter protein level (e.g., 0)",
  },
];
